version: "3"
services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: server
    ports:
      - 3000:3000
    command: ["npm", "run", "start:server", "-w", "server"]
    volumes:
      - vendure_assets:/app/apps/server/static/assets
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: indie-commerce
      DB_USERNAME: postgres
      DB_PASSWORD: 123456

  worker:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: worker
    command: ["npm", "run", "start:worker", "-w", "server"]
    volumes:
      - vendure_assets:/app/apps/server/static/assets
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: indie-commerce
      DB_USERNAME: postgres
      DB_PASSWORD: 123456

  storefront:
    build:
      context: .
      dockerfile: apps/storefront/Dockerfile
      args:
        VENDURE_SHOP_API_URL: http://localhost:3000/shop-api  # 构建时
    container_name: storefront
    ports:
      - 3001:3001
    command: ["node", "apps/storefront/server.js"]
    environment:
      VENDURE_SHOP_API_URL: http://server:3000/shop-api  # 运行时
    depends_on:
      - server

  database:
    image: postgres:16-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: indie-commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d indie-commerce"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  vendure_assets: